### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by Bigpapa100** [LeetIDA/Ez-Ban#1]
FileNotFoundError: [Errno 2] No such file or directory: 'proxy.txt'

**Comment by LeetIDA** [comment]
create a file named proxy.txt

**Comment by Bigpapa100** [comment]
@LeetIDA I created a proxy file and I'm getting this error Something went wrong. It may not be working properly.
Press Enter to close the program

**Comment by Bigpapa100** [comment]
@LeetIDA ←[31m[01:09:57]←[32m Proxy: 165.227.135.39:8080 Report Sent
←[31mSomething went wrong. It may not be working properly.
Press Enter to close the program

**Comment by LeetIDA** [comment]
Can you send screenshots of the showing error?

**Comment by Bigpapa100** [comment]
@LeetIDA of course sir 
![Ekran Görüntüsü (13)](https://github.com/LeetIDA/Ez-Ban/assets/109765995/585f2db9-4d65-44a1-a371-3f98d16f8cdd)
![Ekran Görüntüsü (9)](https://github.com/LeetIDA/Ez-Ban/assets/109765995/a9f7fdc7-810f-4107-8387-b3071676c33a)
![Ekran Görüntüsü (10)](https://github.com/LeetIDA/Ez-Ban/assets/109765995/4c491b49-8472-421c-8148-b77071084bcd)
![Ekran Görüntüsü (11)](https://github.com/LeetIDA/Ez-Ban/assets/109765995/8ca7d096-6d29-4672-88b6-3dbfc983cd22)

**Comment by LeetIDA** [comment]
fixed re try it now and if not working use normal version

**Comment by Bigpapa100** [comment]
@LeetIDA didn't work
