### ISSUE TITLE
'[X] Error: Username Not Found.'

### ISSUE THREAD

**Issue by combatzero** [LeetIDA/Ez-Ban#7]
?

**Comment by LeetIDA** [comment]
It's working fine, can you give me the username to check

**Comment by combatzero** [comment]
https://www.tiktok.com/@magashow1
It's like that in other names too

**Comment by utopi44** [comment]
Error: Username Not Found

**Comment by LeetIDA** [comment]
<img width="1822" alt="image" src="https://github.com/LeetIDA/Ez-Ban/assets/132213924/58ca8104-dfa5-4eda-bbfa-48fb47db5751">


> https://www.tiktok.com/@magashow1 It's like that in other names too

### It's Working Fine You Should Try Update Ruby to Version 3 or try to install the Gems :)

**Comment by combatzero** [comment]
my ruby version 3.2.3
 gem update --system (I did this too, same error again)
